<section class="section section--padding">

    <section id="clients" class="clients-3 section">
        <div class="container">
            <div class="row">
                <div class="preamble col-lg-8 offset-lg-2">
                    <h3 class="title">Ein vertrauenswürdiger Partner</h3>
                    <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    <div class="row justify-content-center">
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/tui.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/schmetterling.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/typisch-touristik.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/codeworx.svgz" alt="" class="img-fluid">
                        </div>
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/kluck-media.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                            <img src="/images/logos/innotrade.jpg" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="testimonials" class="testimonials-5 section">
        <div class="container">
            <div class="row justify-content-center position-relative">
                <div class="d-none d-lg-flex testimonials__button testimonials__prev-button">
                    <svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow"></path></svg>
                </div>
                <div class="d-none d-lg-flex testimonials__button testimonials__next-button">
                    <svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow" transform="translate(100, 100) rotate(180) "></path></svg>
                </div>
                <div class="owl-carousel owl-theme">
                    <?php foreach(json_decode(file_get_contents('data/testimonials.json')) as $testimonial): ?>
                    <div class="d-block d-md-flex justify-content-center">
                        <div class="col-lg-2 col-md-3 text-center text-md-left mb-4 mb-md-0">
                            <div class="blockquote__avatar" style="height: 160px; width: 160px;background-size: cover; background-image: url(<?php echo $testimonial->image; ?>); background-position: top center"></div>
                        </div>
                        <div class="col-lg-7 col-md-9">
                            <blockquote class="blockquote mb-0">
                                <p class="mb-0">"<?php echo $testimonial->testimonial; ?>"</p>
                                <footer>
                                    <h5 class="mb-0 mt-4">— <?php echo $testimonial->contact; ?></h5>
                                    <p class="mb-0"><?php echo $testimonial->job; ?>, <?php echo $testimonial->company; ?></p>
                                </footer>
                            </blockquote>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </section>
</section>