<section id="features" class="features-6 section section--padding section--gradient__4">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Product meets all your needs</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 text-center feature mb-5 mb-lg-0">
                <img src="/images/tour-3.png" alt="" class="feature__image img-fluid">
                <h4 class="mb-3">Complete Solution</h4>
                <p class="pr-4 pl-4">Nail jelly to the hothouse wall best practices. Core competencies core competencies. That jerk from finance really threw me under the bus shoot me an email yet out of.</p>
            </div>
            <div class="col-lg-6 text-center">
                <img src="/images/tour-4.png" alt="" class="feature__image img-fluid">
                <h4 class="mb-3">Mobile Friendly Software</h4>
                <p class="pr-4 pl-4">Drink the Kool-aid. Bake it in close the loop going forward and come up with something buzzworthy face time. Productize this is a no-brainer window-licker, and new economy.</p>
            </div>
        </div>
    </div>
</section>