<main id="main" class="main main-1">
    <nav class="navbar navbar-1 navbar-expand-lg navbar-light justify-content-center">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="../images/logo.png" alt="" class="light">
                <img src="../images/logo.png" alt="" class="dark">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto fill-flex justify-content-center">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Home
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="index.html">Hosting</a>
                            <a class="dropdown-item" href="index2.html">SEO</a>
                            <a class="dropdown-item" href="index3.html">VPN</a>
                            <a class="dropdown-item" href="index4.html">Ecommerce</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#pricing">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#locations">Locations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#integrations">Integrations</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto justify-content-end align-items-start align-items-lg-center">
                    <li class="nav-item">
                        <a class="nav-link nav-link__cta rounded" href="#cta">Kontakt</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="main-content">
        <div class="container">
            <div class="row d-flex align-items-center">
                <div class="col-lg-6 offset-lg-0 col-md-10 offset-md-1 col-sm-10 offset-sm-1 text-center text-lg-left mb-5 mb-lg-0">
                    <div class="pr-0 pr-xl-5 pr-lg-0">
                        <h1 class="main-content__title mb-3 mb-lg-4 h2">Managed Wordpress Hosting bereits ab 29€ / Monat</h1>
                        <p class="main-content__lead lead mb-4">I have zero cycles for this pipeline, so we wanted to see more charts</p>
                        <div class="row d-none d-lg-flex">
                            <div class="col-lg-6 col-md-6">
                                <ul class="features-list list-unstyled m-0">
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">60 Days Free Trials</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">No Credit Card Required</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">All World DataCenter</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-lg-6 col-md-6">
                                <ul class="features-list list-unstyled m-0">
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">Website Page Builder</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">Unlimited Disk Space</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">1 Click Script Installs</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">How it Works<i class="icon icon-Right ml-2"></i></a>
                    </div>
                </div>
                <div class="col-lg-6 text-center text-lg-right position-relative">
                    <img src="../images/hero-illustration-2.png" alt="" class="main-content__img img-fluid">
                </div>
            </div>
        </div>
    </div>
</main>