<main id="main" class="main main-4">
    <div class="gradient"></div>
    <nav class="navbar navbar-1 navbar-expand-lg navbar-light justify-content-center">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="../images/logo.png" alt="" class="light">
                <img src="../images/logo.png" alt="" class="dark">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto fill-flex justify-content-center">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Home
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="index.html">Hosting</a>
                            <a class="dropdown-item" href="index2.html">SEO</a>
                            <a class="dropdown-item" href="index3.html">VPN</a>
                            <a class="dropdown-item" href="index4.html">Ecommerce</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#tour">Tour</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#testimonials">Testimonials</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#pricing">Pricing</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto justify-content-end align-items-start align-items-lg-center">
                    <li class="nav-item">
                        <a class="nav-link nav-link__cta rounded" href="#main">Buy Now</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1">
                    <h1 class="main-content__title mb-3 mb-lg-4 h2">All you need to power your online store with Austin</h1>
                    <p class="main-content__lead lead mb-4">Trusted by over 600,000 businesses worldwide</p>
                    <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">Open new Store<i class="icon icon-Right ml-2"></i></a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <img src="../images/hero-illustration-5.png" alt="" class="img-fluid hero-illustration">
                </div>
            </div>
        </div>
    </div>
    <div class="main-layer">
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none"><polygon points="0,0 50,100 100,0 100,100 0,100"></polygon></svg>
    </div>
</main>