<main id="main" class="main main-4">
    <div class="gradient"></div>

    <?php include_once 'navigation.phtml'; ?>

    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1">
                    <h1 class="main-content__title mb-3 mb-lg-4 h2">Hochperformante und skalierbare Webentwicklung</h1>
                    <p class="main-content__lead lead mb-4">Milzer Solutions entwickelt hochperformante und skalierbare Weblösungen basierend auf Node.js, AngularJS, ExtJS sowie Wordpress und PHP7.</p>
                    <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">Kontakt aufnehmen<i class="icon icon-Right ml-2"></i></a>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <img src="../images/hero-illustration-5.png" alt="" class="img-fluid hero-illustration">
                </div>
            </div>
        </div>
    </div>

    <div class="main-layer">
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none"><polygon points="0,0 50,100 100,0 100,100 0,100"></polygon></svg>
    </div>
</main>