<section id="integrations" class="section section--padding section--gradient__1">
    <div class="container">
        <div class="row">
            <div class="preamble preamble--light col-lg-8 offset-lg-2">
                <h3 class="title">Technologien</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col-lg-5 order-2 order-lg-1 mt-5 mt-lg-0">
                <ul class="features list-unstyled mb-0">
                    <li class="d-flex">
                        <i class="icon icon-Consulting icon--md"></i>
                        <div class="ml-4">
                            <h5>24/7 Real Support</h5>
                            <p>Feature creep going forward you better eat a reality sandwich before you walk back in that boardroom can you send me an invite</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-SSL icon--md"></i>
                        <div class="ml-4">
                            <h5>SSL Domain Certificate</h5>
                            <p>Can you ballpark the cost per unit for me accountable talk bells and whistles, so goalposts for where the metal hits the meat.</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-Wordpress icon--md"></i>
                        <div class="ml-4">
                            <h5>Wordpress One Click</h5>
                            <p>We want to see more charts streamline, or we need to build it so that it scales marketing computer development html roi feedback.</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-7 order-1 order-lg-2">
                <div class="illustration text-right ml-0 ml-xl-5">
                    <img src="../images/circle.png" alt="">
                    <span class="illustration__icons">
                        <img src="../images/integration-1.png" alt="">
                        <img src="../images/integration-2.png" alt="">
                        <img src="../images/integration-3.png" alt="">
                        <img src="../images/integration-4.png" alt="">
                        <img src="../images/integration-5.png" alt="">
                        <img src="../images/integration-6.png" alt="">
                        <img src="../images/integration-7.png" alt="">
                    </span>
                </div>
            </div>
        </div>
    </div>
</section>