<section id="locations">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Milzer Solutions DataCenters Locations</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <img src="../images/map.png" alt="" class="map img-fluid">
                <div class="location location-london" data-toggle="tooltip" data-html="true" title="<h5>London Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>London Data Center</h5><p>England, Europa</p>
                    </div>
                </div>
                <div class="location location-amsterdam" data-toggle="tooltip" data-html="true" title="<h5>Amsterdam Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Amsterdam Data Center</h5><p>Niederlande, Europa</p>
                    </div>
                </div>
                <div class="location location-toronto" data-toggle="tooltip" data-html="true" title="<h5>Toronto Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Toronto Data Center</h5><p>Kanada</p>
                    </div>
                </div>
                <div class="location location-singapore" data-toggle="tooltip" data-html="true" title="<h5>Singapur Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Singapur Data Center</h5><p>Asien</p>
                    </div>
                </div>
                <div class="location location-frankfurt" data-toggle="tooltip" data-html="true" title="<h5>Frankfurt Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Frankfurt Data Center</h5><p>Deutschland, Europa</p>
                    </div>
                </div>
                <div class="location location-sanfrancisco" data-toggle="tooltip" data-html="true" title="<h5>San Francisco Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>San Francisco Data Center</h5><p>USA</p>
                    </div>
                </div>
                <div class="location location-newyork" data-toggle="tooltip" data-html="true" title="<h5>New York Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>New York Data Center</h5><p>USA</p>
                    </div>
                </div>
                <div class="location location-bangalore" data-toggle="tooltip" data-html="true" title="<h5>Bangalore Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Bangalore Data Center</h5><p>Indien</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>