<nav class="navbar navbar-1 navbar-expand-lg navbar-light justify-content-center">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="../images/logo.png" alt="" class="light">
            <img src="../images/logo.png" alt="" class="dark">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto fill-flex justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="#services">Startseite</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#services">Webentwicklung</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tour">Hosting</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#testimonials">Referenzen</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto justify-content-end align-items-start align-items-lg-center">
                <li class="nav-item">
                    <a class="nav-link nav-link__cta rounded" href="#main">Kontakt</a>
                </li>
            </ul>
        </div>
    </div>
</nav>