<section id="pricing" class="pricing pricing-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="pricing-card pricing-card-first">
                    <h5 class="pricing-card__title mb-4">Single</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">29</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>1 Website</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>4GB Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>1000GB Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>50 MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>5 FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>100 Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>Unlimited Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>Unlimited Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>User Friendly Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--blue btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="pricing-card pricing-card-highlighted">
                    <div class="ribbon"><h6 class="text-uppercase mb-0">Meist genutzt</h6></div>
                    <h5 class="pricing-card__title mb-4">Premium</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">49</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Websites</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span><strong>Unlimited</strong> Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span><strong>User Friendly</strong> Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--green btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="pricing-card">
                    <h5 class="pricing-card__title mb-4">Business</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">99</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Websites</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>User Friendly</strong> Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--blue btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>