<section id="services" class="services services-3 section section--padding">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Unsere Leistungen</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="service col-lg-4 mb-5 mb-lg-0">
                <i class="service__icon icon icon--lg icon-Hipster-Men icon--color d-flex"></i>
                <h4 class="service__header">Node.js® Entwicklung</h4>
                <p class="service__text pr-4">
                    Make sure to include in your wheelhouse i also believe it's important for every member to be involved and invested in our company and this is one way.             </p>
                <ul class="service__list list-unstyled mb-0">
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Design</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Applications</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Digital Strategy</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Information Architecture</li>
                </ul>
            </div>

            <div class="service col-lg-4 mb-5 mb-lg-0">
                <i class="service__icon icon icon--lg icon-Atom icon--color d-flex"></i>
                <h4 class="service__header">Frontend & Backend</h4>
                <p class="service__text pr-4">
                    It looks a bit empty, try to make everything bigger that sandwich needs to be more playful I really like the colour but can you change it we need.                </p>
                <ul class="service__list list-unstyled mb-0">
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Design</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Applications</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Digital Strategy</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Information Architecture</li>
                </ul>
            </div>
            <div class="service col-lg-4">
                <i class="service__icon icon icon--lg icon-Clouds icon--color d-flex"></i>
                <h4 class="service__header">Cloud Infrastruktur</h4>
                <p class="service__text pr-4">
                    Is this the best we can do you might wanna give it another shot, low resolution? It looks ok on my screen , nor can you punch up the fun level on these icons.
                </p>
                <ul class="service__list list-unstyled mb-0">
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Design</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Web Applications</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Digital Strategy</li>
                    <li class="d-flex align-items-center"><i class="icon icon-Right mr-3"></i>Information Architecture</li>
                </ul>
            </div>
        </div>
    </div>
</section>