<section id="testimonials" class="testimonials-1 section section--gradient__4">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col-lg-6 order-2 order-lg-1">
                <img src="../images/simon.png" alt="" class="img-fluid">
            </div>
            <div class="col-lg-6 order-1 order-lg-2">
                <blockquote class="blockquote">
                    <p class="mb-0">"Wir vereinfachen das Hosting, weil wir daran glauben, Einzelpersonen, Teams und Unternehmen zu stärken. Wir setzen hohe Leistungsstandards, gepaart mit Einfachheit und Agilität in jedem Prozess. Unterstützt durch einen innovativen Ansatz basiert unsere Plattform auf den besten Technologien und branchenführenden Infrastrukturanbietern, die ein reibungsloses Managed Cloud Hosting ermöglichen."</p>
                    <footer>
                        <h5 class="mb-0 mt-4">— Simon Milz</h5>
                        <p>Gründer und Geschäftsführer</p>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
</section>