<section id="clients" class="clients-1 section section--padding__bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-11">
                <div class="row">
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="integrations" class="section section--padding section--gradient__1">
    <div class="container">
        <div class="row">
            <div class="preamble preamble--light col-lg-8 offset-lg-2">
                <h3 class="title">Integrations</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col-lg-5 order-2 order-lg-1 mt-5 mt-lg-0">
                <ul class="features list-unstyled mb-0">
                    <li class="d-flex">
                        <i class="icon icon-Consulting icon--md"></i>
                        <div class="ml-4">
                            <h5>24/7 Real Support</h5>
                            <p>Feature creep going forward you better eat a reality sandwich before you walk back in that boardroom can you send me an invite</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-SSL icon--md"></i>
                        <div class="ml-4">
                            <h5>SSL Domain Certificate</h5>
                            <p>Can you ballpark the cost per unit for me accountable talk bells and whistles, so goalposts for where the metal hits the meat.</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-Wordpress icon--md"></i>
                        <div class="ml-4">
                            <h5>Wordpress One Click</h5>
                            <p>We want to see more charts streamline, or we need to build it so that it scales marketing computer development html roi feedback.</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-7 order-1 order-lg-2">
                <div class="illustration text-right ml-0 ml-xl-5">
                    <img src="http://via.placeholder.com/1206x1166" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

<section id="charts" class="section section--padding">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Performance Comparison</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>UnixBench Scores</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>Performance Per Dollar</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart2" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-lg-0">
                <header class="chart-header">
                    <h5>I/O Benchmark</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart3" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
</section>