<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700%7COpen+Sans:400,600" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="../css/iconsmind.css">
    <link rel="stylesheet" href="../css/main.css">
    <link rel="stylesheet" href="../css/socicons.css">

    <title>Hosting Landing Page</title>
</head>
<body class="body-2">

<section id="promo" class="d-none d-lg-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="mb-0 d-flex align-items-center justify-content-center"><label class="badge badge-secondary mr-3">HOT</label> Try Austin for 14 days. <span class="d-none d-lg-inline-block">No risk, and no credit card required. Hosting for 3 months for free</span></p>
            </div>
        </div>
    </div>
    <i class="icon icon-Close-Window"></i>
</section>

<main id="main" class="main main-1">
    <nav class="navbar navbar-1 navbar-expand-lg navbar-light justify-content-center">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="../images/logo.png" alt="" class="light">
                <img src="../images/logo.png" alt="" class="dark">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto fill-flex justify-content-center">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Home
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="index.html">Hosting</a>
                            <a class="dropdown-item" href="index2.html">SEO</a>
                            <a class="dropdown-item" href="index3.html">VPN</a>
                            <a class="dropdown-item" href="index4.html">Ecommerce</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#pricing">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#locations">Locations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#integrations">Integrations</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto justify-content-end align-items-start align-items-lg-center">
                    <li class="nav-item">
                        <a class="nav-link nav-link__cta rounded" href="#cta">Kontakt</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="main-content">
        <div class="container">
            <div class="row d-flex align-items-center">
                <div class="col-lg-6 offset-lg-0 col-md-10 offset-md-1 col-sm-10 offset-sm-1 text-center text-lg-left mb-5 mb-lg-0">
                    <div class="pr-0 pr-xl-5 pr-lg-0">
                        <h1 class="main-content__title mb-3 mb-lg-4 h2">Managed Wordpress Hosting bereits ab 29€ / Monat</h1>
                        <p class="main-content__lead lead mb-4">I have zero cycles for this pipeline, so we wanted to see more charts</p>
                        <div class="row d-none d-lg-flex">
                            <div class="col-lg-6 col-md-6">
                                <ul class="features-list list-unstyled m-0">
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">60 Days Free Trials</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">No Credit Card Required</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">All World DataCenter</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-lg-6 col-md-6">
                                <ul class="features-list list-unstyled m-0">
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">Website Page Builder</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">Unlimited Disk Space</span>
                                    </li>
                                    <li class="features-list__item d-flex align-items-center">
                                        <i class="features-list__item--icon mr-2"></i>
                                        <span class="features-list__item--text color--white">1 Click Script Installs</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">How it Works<i class="icon icon-Right ml-2"></i></a>
                    </div>
                </div>
                <div class="col-lg-6 text-center text-lg-right position-relative">
                    <img src="../images/hero-illustration-2.png" alt="" class="main-content__img img-fluid">
                </div>
            </div>
        </div>
    </div>
</main>

<section id="pricing" class="pricing pricing-1">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="pricing-card pricing-card-first">
                    <h5 class="pricing-card__title mb-4">Single</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">29</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>1 Website</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>4GB Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>1000GB Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>50 MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>5 FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span>100 Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>Unlimited Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>Unlimited Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span>User Friendly Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--blue btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="pricing-card pricing-card-highlighted">
                    <div class="ribbon"><h6 class="text-uppercase mb-0">Meist genutzt</h6></div>
                    <h5 class="pricing-card__title mb-4">Premium</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">49</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Websites</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span><strong>Unlimited</strong> Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__false mr-2"></i>
                            <span><strong>User Friendly</strong> Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--green btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="pricing-card">
                    <h5 class="pricing-card__title mb-4">Business</h5>
                    <h3 class="pricing-card__value"><span class="pricing-currency">€</span><span class="pricing-cost">99</span><span class="pricing-period">/mo</span></h3>
                    <ul class="pricing-card__list list-unstyled mb-0 pb-1">
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Websites</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Disk Space</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Bandwidth</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> MySQL Database</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> FTP User</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Email Account</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Website Builder</span>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>Unlimited</strong> Control Panel</span>
                            <i data-feather="help-circle" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <i class="pricing-icon pricing-icon__true mr-2"></i>
                            <span><strong>User Friendly</strong> Access Manager</span>
                        </li>
                    </ul>
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn--blue btn--lg">Get Started</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="clients" class="clients-1 section section--padding__bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-11">
                <div class="row">
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="locations">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Milzer Solutions DataCenters Locations</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <img src="../images/map.png" alt="" class="map img-fluid">
                <div class="location location-london" data-toggle="tooltip" data-html="true" title="<h5>London Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>London Data Center</h5><p>England, Europa</p>
                    </div>
                </div>
                <div class="location location-amsterdam" data-toggle="tooltip" data-html="true" title="<h5>Amsterdam Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Amsterdam Data Center</h5><p>Niederlande, Europa</p>
                    </div>
                </div>
                <div class="location location-toronto" data-toggle="tooltip" data-html="true" title="<h5>Toronto Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Toronto Data Center</h5><p>Kanada</p>
                    </div>
                </div>
                <div class="location location-singapore" data-toggle="tooltip" data-html="true" title="<h5>Singapur Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Singapur Data Center</h5><p>Asien</p>
                    </div>
                </div>
                <div class="location location-frankfurt" data-toggle="tooltip" data-html="true" title="<h5>Frankfurt Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Frankfurt Data Center</h5><p>Deutschland, Europa</p>
                    </div>
                </div>
                <div class="location location-sanfrancisco" data-toggle="tooltip" data-html="true" title="<h5>San Francisco Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>San Francisco Data Center</h5><p>USA</p>
                    </div>
                </div>
                <div class="location location-newyork" data-toggle="tooltip" data-html="true" title="<h5>New York Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>New York Data Center</h5><p>USA</p>
                    </div>
                </div>
                <div class="location location-bangalore" data-toggle="tooltip" data-html="true" title="<h5>Bangalore Data Center</h5>">
                    <div class="location__pin"></div>
                    <div class="location__rwd d-block d-md-none">
                        <h5>Bangalore Data Center</h5><p>Indien</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="features" class="features-1 section section--padding__wmargin">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-CPU icon--color mr-4"></i>
                    <div>
                        <h5>100% Intel Cores</h5>
                        <p class="pr-4">Diversify kpis gain traction, so anti-pattern and get all your ducks.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-Billing icon--color mr-4"></i>
                    <div>
                        <h5>No long term contracts</h5>
                        <p class="pr-4">Shoot me an email we've got to manage that low hanging fruit that jerk.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-Atom icon--color mr-4"></i>
                    <div>
                        <h5>Powerful API</h5>
                        <p class="pr-4">Powerpoint Bunny we need distributors to evangelize the new line to local markets.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-Restore-Window icon--color mr-4"></i>
                    <div>
                        <h5>Whenever something happens</h5>
                        <p class="pr-4">We need more paper drill down, yet t-shaped individual nor are we in agreeance.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-Data-Lock icon--color mr-4"></i>
                    <div>
                        <h5>Root administrator access</h5>
                        <p class="pr-4">Dog and pony show your work on this project has been really impactful quick win.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="feature d-flex">
                    <i class="feature__icon icon icon--md icon-Target icon--color mr-4"></i>
                    <div>
                        <h5>Infinite OS combinations</h5>
                        <p class="pr-4">Time to open the kimono I have zero cycles for this. Where do we stand on the latest client ask.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="integrations" class="section section--padding section--gradient__1">
    <div class="container">
        <div class="row">
            <div class="preamble preamble--light col-lg-8 offset-lg-2">
                <h3 class="title">Integrations</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col-lg-5 order-2 order-lg-1 mt-5 mt-lg-0">
                <ul class="features list-unstyled mb-0">
                    <li class="d-flex">
                        <i class="icon icon-Consulting icon--md"></i>
                        <div class="ml-4">
                            <h5>24/7 Real Support</h5>
                            <p>Feature creep going forward you better eat a reality sandwich before you walk back in that boardroom can you send me an invite</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-SSL icon--md"></i>
                        <div class="ml-4">
                            <h5>SSL Domain Certificate</h5>
                            <p>Can you ballpark the cost per unit for me accountable talk bells and whistles, so goalposts for where the metal hits the meat.</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-Wordpress icon--md"></i>
                        <div class="ml-4">
                            <h5>Wordpress One Click</h5>
                            <p>We want to see more charts streamline, or we need to build it so that it scales marketing computer development html roi feedback.</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-7 order-1 order-lg-2">
                <div class="illustration text-right ml-0 ml-xl-5">
                    <img src="http://via.placeholder.com/1206x1166" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

<section id="charts" class="section section--padding">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Performance Comparison</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>UnixBench Scores</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>Performance Per Dollar</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart2" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-lg-0">
                <header class="chart-header">
                    <h5>I/O Benchmark</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart3" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
</section>

<section id="testimonials" class="testimonials-1 section section--gradient__4">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col-lg-6 order-2 order-lg-1">
                <img src="../images/simon.png" alt="" class="img-fluid">
            </div>
            <div class="col-lg-6 order-1 order-lg-2">
                <blockquote class="blockquote">
                    <p class="mb-0">"Wir vereinfachen das Hosting, weil wir daran glauben, Einzelpersonen, Teams und Unternehmen zu stärken. Wir setzen hohe Leistungsstandards, gepaart mit Einfachheit und Agilität in jedem Prozess. Unterstützt durch einen innovativen Ansatz basiert unsere Plattform auf den besten Technologien und branchenführenden Infrastrukturanbietern, die ein reibungsloses Managed Cloud Hosting ermöglichen."</p>
                    <footer>
                        <h5 class="mb-0 mt-4">— Simon Milz</h5>
                        <p>Gründer und Geschäftsführer</p>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
</section>

<section id="cta" class="cta-1 section section--padding section--gradient__2">
    <div class="container">
        <div class="row">
            <div class="preamble preamble--light col-lg-8 offset-lg-2 mb-5">
                <h3 class="title">Get Austin Enterprise</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <form action="#" class="footer-form mb-0">
                    <div class="form-group">
                        <label class="footer-form__label" for="name">Full Name <span class="required">*</span></label>
                        <input type="text" class="form-control footer-form__input" id="name" aria-describedby="name" required>
                    </div>
                    <div class="form-group">
                        <label class="footer-form__label" for="email">Email Address <span class="required">*</span></label>
                        <input type="email" class="form-control footer-form__input" id="email" aria-describedby="email" required>
                    </div>
                    <div class="form-group">
                        <label class="footer-form__label" for="number">Phone Number <span class="required">*</span></label>
                        <input type="number" class="form-control footer-form__input" id="number" aria-describedby="number" required>
                    </div>
                    <div class="form-group justify-content-center d-flex mt-4">
                        <button class="btn btn--blue btn--lg w-100">Start your Trial</button>
                    </div>
                    <small class="d-block text-center">Signing up signifies you have read and agree to our
                        Terms of Service and <a href="#">Privacy Policy.</a></small>
                </form>
            </div>
        </div>
    </div>
</section>

<footer id="footer" class="footer-1">
    <div class="container">
        <div class="row d-block d-md-flex align-items-center fill-flex">
            <div class="col justify-content-center justify-content-md-start d-flex mb-3 mb-md-0">
                <div class="footer__contact d-flex align-items-center">
                    <i class="icon icon-Phone"></i>
                    <p class="mb-0 ml-3">+48 543 654 432</p>
                </div>
            </div>
            <div class="col justify-content-center justify-content-md-center d-flex mb-3 mb-md-0">
                <p class="footer__copyrights mb-0">2018. Created by PeElOne</p>
            </div>
            <div class="col justify-content-center justify-content-md-end d-flex">
                <ul class="footer__social list-unstyled m-0 d-flex">
                    <li>
                        <a href="#">
                            <i class="socicon-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="socicon-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="socicon-skype"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="socicon-disqus"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="socicon-medium"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<div class="modal fade" id="newsletterModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body">
                <div class="row no-gutters">
                    <div class="modal-body__image col-md-5"></div>
                    <div class="modal-body__content col-md-7">
                        <div class="d-flex justify-content-center">
                            <div class="col-lg-9 col-md-8">
                                <div class="preamble text-left mb-5">
                                    <h3 class="title">Just 24 Hours Left!</h3>
                                    <p class="lead">Your limited-time offer to upgrade to Austin Premium is almost up.</p>
                                </div>
                                <form action="#" class="modal__form">
                                    <div class="form-group">
                                        <input type="text" placeholder="Your Name" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="email" placeholder="Your Email" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group justify-content-center d-flex mt-3 mb-0">
                                        <button class="btn btn--blue btn--lg w-100 modal__form--btn">Join Newsletter Now</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="../js/main.js"></script>
</body>
</html>