<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700%7COpen+Sans:400,600" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/css/iconsmind.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/socicons.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">

    <title>Milzer Solutions - Enterprise Software Engineering</title>
</head>
<body class="body-2">

<section id="promo" class="d-none d-lg-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="mb-0 d-flex align-items-center justify-content-center"><label class="badge badge-secondary mr-3">HOT</label> Try Austin for 14 days. <span class="d-none d-lg-inline-block">No risk, and no credit card required. Hosting for 3 months for free</span></p>
            </div>
        </div>
    </div>
    <i class="icon icon-Close-Window"></i>
</section>

<?php include_once 'sections/header-4.phtml'; ?>
<?php include_once 'sections/services.phtml'; ?>
<?php include_once 'sections/features.phtml'; ?>
<?php include_once 'sections/clients-and-testimonials.phtml'; ?>

<section id="clients" class="clients-1 section section--padding__bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-11">
                <div class="row">
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-4 col-6 d-flex align-items-center justify-content-center">
                        <img src="http://via.placeholder.com/215x47" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="integrations" class="section section--padding section--gradient__1">
    <div class="container">
        <div class="row">
            <div class="preamble preamble--light col-lg-8 offset-lg-2">
                <h3 class="title">Integrations</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col-lg-5 order-2 order-lg-1 mt-5 mt-lg-0">
                <ul class="features list-unstyled mb-0">
                    <li class="d-flex">
                        <i class="icon icon-Consulting icon--md"></i>
                        <div class="ml-4">
                            <h5>24/7 Real Support</h5>
                            <p>Feature creep going forward you better eat a reality sandwich before you walk back in that boardroom can you send me an invite</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-SSL icon--md"></i>
                        <div class="ml-4">
                            <h5>SSL Domain Certificate</h5>
                            <p>Can you ballpark the cost per unit for me accountable talk bells and whistles, so goalposts for where the metal hits the meat.</p>
                        </div>
                    </li>
                    <li class="d-flex">
                        <i class="icon icon-Wordpress icon--md"></i>
                        <div class="ml-4">
                            <h5>Wordpress One Click</h5>
                            <p>We want to see more charts streamline, or we need to build it so that it scales marketing computer development html roi feedback.</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-lg-7 order-1 order-lg-2">
                <div class="illustration text-right ml-0 ml-xl-5">
                    <img src="http://via.placeholder.com/1206x1166" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

<section id="charts" class="section section--padding">
    <div class="container">
        <div class="row">
            <div class="preamble col-lg-8 offset-lg-2">
                <h3 class="title">Performance Comparison</h3>
                <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>UnixBench Scores</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-md-0">
                <header class="chart-header">
                    <h5>Performance Per Dollar</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart2" width="400" height="400"></canvas>
            </div>
            <div class="col-lg-4 col-md-6 mt-5 mt-lg-0">
                <header class="chart-header">
                    <h5>I/O Benchmark</h5>
                    <p>higher is better</p>
                </header>
                <canvas id="myChart3" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
</section>

<footer id="footer" class="footer-4 section--gradient__3">
    <div class="footer__top section section--padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <img src="../images/logo.png" alt="" class="footer__logo img-fluid">
                </div>
                <div class="preamble preamble--light mb-4 col-lg-10 offset-lg-1">
                    <h3 class="title">Everything you need<br> to revolutionize your website</h3>
                    <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
                    <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">Get This Theme<i class="icon icon-Right ml-2"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__bottom">
        <div class="container">
            <div class="row">
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Truly Unlimited</h5>
                    <p>Make as many sites as you want.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Forever Yours</h5>
                    <p>Pay once with no tricky charges.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">5 Star Support</h5>
                    <p>20-day money back guarantee.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Frequent Updates</h5>
                    <p>We make it better. Constantly.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="modal fade" id="newsletterModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body">
                <div class="row no-gutters">
                    <div class="modal-body__image col-md-5"></div>
                    <div class="modal-body__content col-md-7">
                        <div class="d-flex justify-content-center">
                            <div class="col-lg-9 col-md-8">
                                <div class="preamble text-left mb-5">
                                    <h3 class="title">Just 24 Hours Left!</h3>
                                    <p class="lead">Your limited-time offer to upgrade to Austin Premium is almost up.</p>
                                </div>
                                <form action="#" class="modal__form">
                                    <div class="form-group">
                                        <input type="text" placeholder="Your Name" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="email" placeholder="Your Email" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group justify-content-center d-flex mt-3 mb-0">
                                        <button class="btn btn--blue btn--lg w-100 modal__form--btn">Join Newsletter Now</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/js/main.js"></script>
</body>
</html>