<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700%7COpen+Sans:400,600" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/css/iconsmind.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/socicons.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">

    <title>Milzer Solutions - Enterprise Software Engineering</title>
</head>
<body class="body-2">

<section id="promo" class="d-none d-lg-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="mb-0 d-flex align-items-center justify-content-center"><label class="badge badge-secondary mr-3">HOT</label> Try Austin for 14 days. <span class="d-none d-lg-inline-block">No risk, and no credit card required. Hosting for 3 months for free</span></p>
            </div>
        </div>
    </div>
    <i class="icon icon-Close-Window"></i>
</section>

<?php include_once 'sections/header-4.phtml'; ?>
<?php include_once 'sections/services.phtml'; ?>
<?php include_once 'sections/integrations.phtml'; ?>
<?php include_once 'sections/features.phtml'; ?>
<?php include_once 'sections/clients-and-testimonials.phtml'; ?>

<footer id="footer" class="footer-4 section--gradient__3">
    <div class="footer__top section section--padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <img src="../images/logo.png" alt="" class="footer__logo img-fluid">
                </div>
                <div class="preamble preamble--light mb-4 col-lg-10 offset-lg-1">
                    <h3 class="title">Everything you need<br> to revolutionize your website</h3>
                    <p class="lead">Demonstrating core competencies to in turn innovate. Create stakeholder engagement so that we gain traction.</p>
                    <a href="#" class="btn btn--green btn--lg mb-0 mt-4 d-inline-flex align-items-center">Get This Theme<i class="icon icon-Right ml-2"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__bottom">
        <div class="container">
            <div class="row">
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Truly Unlimited</h5>
                    <p>Make as many sites as you want.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Forever Yours</h5>
                    <p>Pay once with no tricky charges.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">5 Star Support</h5>
                    <p>20-day money back guarantee.</p>
                </div>
                <div class="footer__feature col-lg-3 col-md-6 text-center text-lg-left">
                    <h5 class="color--white">Frequent Updates</h5>
                    <p>We make it better. Constantly.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="modal fade" id="newsletterModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body">
                <div class="row no-gutters">
                    <div class="modal-body__image col-md-5"></div>
                    <div class="modal-body__content col-md-7">
                        <div class="d-flex justify-content-center">
                            <div class="col-lg-9 col-md-8">
                                <div class="preamble text-left mb-5">
                                    <h3 class="title">Just 24 Hours Left!</h3>
                                    <p class="lead">Your limited-time offer to upgrade to Austin Premium is almost up.</p>
                                </div>
                                <form action="#" class="modal__form">
                                    <div class="form-group">
                                        <input type="text" placeholder="Your Name" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="email" placeholder="Your Email" class="form-control modal__form--input" required>
                                    </div>
                                    <div class="form-group justify-content-center d-flex mt-3 mb-0">
                                        <button class="btn btn--blue btn--lg w-100 modal__form--btn">Join Newsletter Now</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/js/main.js"></script>
</body>
</html>